### ISSUE TITLE
[Nexus3] Failed to update nexus3 3.33.0 to 3.38.1

### ISSUE THREAD

**Issue by GabrielAmaral** [stevehipwell/helm-charts#519] opened 2022-09-26 19:40 UTC
Hi,

I'm trying to update my nexus3 from 3.33.0 (chart version 4.5.0) to 3.38.1 (chart version 4.11.1) but I get an error "Could not update root password".
What I've noticed is that when I connect via SSH into the pod, I try to make cURL calls and get 503 or 000 in response.
I've tried to identify in several ways what is happening, but I couldn't find it.
Anyone had this problem?

[podError.txt](https://github.com/stevehipwell/helm-charts/files/9649183/podError.txt)

**Comment by stevehipwell** [comment] 2022-09-26 22:10
Is this a duplicate of #518?

**Closed** 2022-09-27 18:38 UTC
